<?php

    include '../config.php';

    $Task_ID = $_GET['Task_ID'] ;
    if($Task_ID==NULL)
        $sel = mysqli_query($db,"select * from task_data INNER JOIN Task_Status ON task_data.TASK_ID = Task_Status.TASK_ID");
    else
        $sel = mysqli_query($db,"select * from task_data INNER JOIN Task_Status ON task_data.TASK_ID = Task_Status.TASK_ID  WHERE task_data.TASK_ID =  '$Task_ID'");
    $data = array();

    while ($row = mysqli_fetch_array($sel)) {
    $data[] = array(

            "TASK_ID"=>(int)$row['TASK_ID'],
            "WO"=>(int)$row['WO'],
            "WO_DATE"=>$row['WO_DATE'],
            "WO_TYPE"=>$row['WO_TYPE'],
            "WO_SHORT_TEXT"=>$row['WO_SHORT_TEXT'],
            "AREA"=>$row['AREA'],
            "PHASE"=>$row['PHASE'],
            "PLANT_SECTION"=>$row['PLANT_SECTION'],
            "MWC"=>$row['MWC'],
            "WBS"=>$row['WBS'],
            "PLAN_START"=>$row['PLAN_START'],
            "PLAN_FINISH"=>$row['PLAN_FINISH'],
            "F_LOCATION"=>$row['F_LOCATION'],
            "SHORT_NOTES"=>$row['SHORT_NOTES'],
            "SHIFT_MODE"=>$row['SHIFT_MODE'],
            "NOTICE_48H"=>(int)$row['NOTICE_48H'],
            "REMARKS"=>(int)$row['REMARKS'],
            "CAT_1"=>$row['CAT_1'],
            "CAT_2"=>$row['CAT_2'],
            "CAT_3"=>$row['CAT_3'],
            "CONFINED"=>$row['CONFINED'],
            "START_ELE"=>(float)$row['START_ELE'],
            "LENGTH"=>(float)$row['LENGTH'],
            "WIDTH"=>(float)$row['WIDTH'],
            "HEIGHT"=>(float)$row['HEIGHT'],
            "NPF0_6M"=>(float)$row['NPF0_6M'],
            "NPF6_18M"=>(float)$row['NPF6_18M'],
            "NPF18_30M"=>(float)$row['NPF18_30M'],
            "NPF30_42M"=>(float)$row['NPF30_42M'],
            "NPF_42_100M"=>(float)$row['NPF_42_100M'],
            "ERE_DATE"=>$row['ERE_DATE'],
            "OFF_DATE"=>$row['OFF_DATE'],
            "DIS_DATE"=>$row['DIS_DATE'],
            "TOP_ELE"=>(float)$row['TOP_ELE'],
            "ELE_FACTOR"=>(float)$row['ELE_FACTOR'],
            "CON_FACTOR"=>(float)$row['CON_FACTOR'],
            "DURATION"=>(int)$row['DURATION'],
            "HIRE_30D"=>(int)$row['HIRE_30D'],
            "HIRE_90D"=>(int)$row['HIRE_90D'],
            "HIRE_180D"=>(int)$row['HIRE_180D'],
            "HIRE_365D"=>(int)$row['HIRE_365D'],
            "HIRE_730D"=>(int)$row['HIRE_730D'],
            "QTY_STR0_6M"=>(float)$row['QTY_STR0_6M'],
            "QTY_STR6_18M"=>(float)$row['QTY_STR6_18M'],
            "QTY_STR18_30M"=>(float)$row['QTY_STR18_30M'],
            "QTY_STR30_42M"=>(float)$row['QTY_STR30_42M'],
            "QTY_STR_42_100M"=>(float)$row['QTY_STR_42_100M'],
            "QTY_BRD0_6M"=>(float)$row['QTY_BRD0_6M'],
            "QTY_BRD6_18M"=>(float)$row['QTY_BRD6_18M'],
            "QTY_BRD18_30M"=>(float)$row['QTY_BRD18_30M'],
            "QTY_BRD30_42M"=>(float)$row['QTY_BRD30_42M'],
            "QTY_BRD_42_100M"=>(float)$row['QTY_BRD_42_100M'],
            "ER_STR0_6M"=>(float)$row['ER_STR0_6M'],
            "ER_STR6_18M"=>(float)$row['ER_STR6_18M'],
            "ER_STR18_30M"=>(float)$row['ER_STR18_30M'],
            "ER_STR30_42M"=>(float)$row['ER_STR30_42M'],
            "ER_STR_42_100M"=>(float)$row['ER_STR_42_100M'],
            "ER_BRD0_6M"=>(float)$row['ER_BRD0_6M'],
            "ER_BRD6_18M"=>(float)$row['ER_BRD6_18M'],
            "ER_BRD18_30M"=>(float)$row['ER_BRD18_30M'],
            "ER_BRD30_42M"=>(float)$row['ER_BRD30_42M'],
            "ER_BRD_42_100M"=>(float)$row['ER_BRD_42_100M'],
            "HIRE_STR0_6M"=>(float)$row['HIRE_STR0_6M'],
            "HIRE_STR6_18M"=>(float)$row['HIRE_STR6_18M'],
            "HIRE_STR18_30M"=>(float)$row['HIRE_STR18_30M'],
            "HIRE_STR30_42M"=>(float)$row['HIRE_STR30_42M'],
            "HIRE_STR_42_100M"=>(float)$row['HIRE_STR_42_100M'],
            "HIRE_BRD0_6M"=>(float)$row['HIRE_BRD0_6M'],
            "HIRE_BRD6_18M"=>(float)$row['HIRE_BRD6_18M'],
            "HIRE_BRD18_30M"=>(float)$row['HIRE_BRD18_30M'],
            "HIRE_BRD30_42M"=>(float)$row['HIRE_BRD30_42M'],
            "HIRE_BRD_42_100M"=>(float)$row['HIRE_BRD_42_100M'],
            "DR_STR0_6M"=>(float)$row['DR_STR0_6M'],
            "DR_STR6_18M"=>(float)$row['DR_STR6_18M'],
            "DR_STR18_30M"=>(float)$row['DR_STR18_30M'],
            "DR_STR30_42M"=>(float)$row['DR_STR30_42M'],
            "DR_STR_42_100M"=>(float)$row['DR_STR_42_100M'],
            "DR_BRD0_6M"=>(float)$row['DR_BRD0_6M'],
            "DR_BRD6_18M"=>(float)$row['DR_BRD6_18M'],
            "DR_BRD18_30M"=>(float)$row['DR_BRD18_30M'],
            "DR_BRD30_42M"=>(float)$row['DR_BRD30_42M'],
            "DR_BRD_42_100M"=>(float)$row['DR_BRD_42_100M'],
            "ERE_AMT_TOTAL"=>(float)$row['ERE_AMT_TOTAL'],
            "HIRE_AMT_TOTAL"=>(float)$row['HIRE_AMT_TOTAL'],
            "DIS_AMT_TOTAL"=>(float)$row['DIS_AMT_TOTAL'],
            "TOTAL_AMT"=>(float)$row['TOTAL_AMT'],
            "ERE_AMT_PRE"=>(float)$row['ERE_AMT_PRE'],
            "HIRE_AMT_PRE"=>(float)$row['HIRE_AMT_PRE'],
            "DIS_AMT_PRE"=>(float)$row['DIS_AMT_PRE'],
            "TOTAL_AMT_PRE"=>(float)$row['TOTAL_AMT_PRE'],
            "TASK_STATUS"=>$row['STATUS']
        );
        }
    echo json_encode($data);
?>